In [1]:
import pandas as pd

In [2]:
### R에서 데이터가 불러들이기 힘들어서 파이썬으로 먼저 작업
### Unnamed 컬럼이 문제의 컬럼이므로 이를 삭제하고 다시 csv로 저장
df=pd.read_csv('../DICT.csv', sep=',', encoding='utf-8')
df.head()

,Unnamed: 0,word_id,의미어,표제어,의미번호,뜻풀이,품사,난이도
0,1,1,ㄱ001,ㄱ,1,"한글 자모의 첫째 글자. 기역이라 이르며, ‘가’에서와 같이 초성으로, ‘역’에서와...",명사,상
1,2,2,ㄱㄴㄷ순001,ㄱㄴㄷ-순,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상
2,3,3,ㄱㄴㄷ차례001,ㄱㄴㄷ-차례,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상
3,4,4,ㄱㄴ순001,ㄱㄴ-순,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상
4,5,5,ㄱㄴ차례001,ㄱㄴ-차례,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상

In [3]:
del df['Unnamed: 0']

In [4]:
df.head()

,word_id,의미어,표제어,의미번호,뜻풀이,품사,난이도
0,1,ㄱ001,ㄱ,1,"한글 자모의 첫째 글자. 기역이라 이르며, ‘가’에서와 같이 초성으로, ‘역’에서와...",명사,상
1,2,ㄱㄴㄷ순001,ㄱㄴㄷ-순,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상
2,3,ㄱㄴㄷ차례001,ㄱㄴㄷ-차례,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상
3,4,ㄱㄴ순001,ㄱㄴ-순,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상
4,5,ㄱㄴ차례001,ㄱㄴ-차례,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상

In [5]:
df.to_csv('../DICT001.csv',header=True,index=False)

In [6]:
### 다시 확인 차 불러들임
df1=pd.read_csv('../DICT001.csv', sep=',', encoding='utf-8')
df1.head()

,word_id,의미어,표제어,의미번호,뜻풀이,품사,난이도
0,1,ㄱ001,ㄱ,1,"한글 자모의 첫째 글자. 기역이라 이르며, ‘가’에서와 같이 초성으로, ‘역’에서와...",명사,상
1,2,ㄱㄴㄷ순001,ㄱㄴㄷ-순,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상
2,3,ㄱㄴㄷ차례001,ㄱㄴㄷ-차례,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상
3,4,ㄱㄴ순001,ㄱㄴ-순,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상
4,5,ㄱㄴ차례001,ㄱㄴ-차례,1,"한글의 ‘ㄱ, ㄴ, ㄷ……’ 차례로 매기는 순서.",명사,상

In [2]:
keyData=pd.read_csv('../EZmeta30.csv', sep=',', encoding='utf-8')
keyData.head()

,pair_id,표제어 kword_id,표제어,의미번호,표제어 난이도,relation2,관련어 word_id,관련어,의미번호.1,관련어 난이도
0,1,2184,가톨릭,2,하,비슷한말,97798,서학,2,중
1,2,2186,가톨릭-교,1,중,비슷한말,16023,공교,2,상
2,3,2186,가톨릭-교,1,중,비슷한말,182393,천주-학,1,중
3,4,2186,가톨릭-교,1,중,비슷한말,176596,진교,2,상
4,5,2188,가톨릭-교도,1,중,비슷한말,182378,천좍-쟁이,1,상

In [3]:
keyData.to_csv('../EZmeta31.csv',header=True,index=False)

In [1]:
import konlpy